language: php

os:   linux
dist: bionic
sudo: required

php:
    - '7.3'

branches:
    only:
        - develop

cache:
    yarn: true
    directories:
        - ${HOME}/.composer/cache/files
        - node_modules

install:
    - >
        yarn install
        --production
    - >
        yarn encore
        production
    - >
        composer install
        --prefer-dist
        --no-ansi
        --no-dev
        --no-interaction
        --no-progress
        --optimize-autoloader
    - >
        vendor/bin/sculpin generate
        --env=prod
    - >
        vendor/bin/sculpin serve
        --port=8080
        --no-ansi
        --no-interaction

script:
    - >
        vendor/bin/behat
        --config=behat.yml.dist

deploy:
    provider:      pages
    skip_cleanup:  true
    github_token:  ${GITHUB_TOKEN}
    local_dir:     output_prod
    target_branch: master
    on:
        branch: develop
