language: php

os:   linux
dist: bionic
sudo: required

branches:
    only:
        - develop

cache:
    directories:
        - ${HOME}/.composer/cache/files

php:
    - '7.3'

install:
    - composer install

script:
    - vendor/bin/sculpin generate --env=prod

deploy:
    provider:       pages
    skip_cleanup:   true
    github_token:   ${GITHUB_TOKEN}
    local_dir:      output_prod
    target-branch:  master
    on:
        branch: develop
