language: php

os:   linux
dist: bionic
sudo: required

php:
    - '7.4'

env:
    - PACKAGE_NODE="15.7.0"

branches:
    only:
        - develop

cache:
    yarn: true
    directories:
        - ${HOME}/.composer/cache/files
        - node_modules

before_install:
    - nvm install ${PACKAGE_NODE}

install:
    - >
        yarn install
    - >
        yarn encore
        dev
    - >
        composer install
        --prefer-dist
        --no-ansi
        --no-interaction
        --no-progress
        --ignore-platform-req php
    - >
        vendor/bin/sculpin generate
        --env=${APP_ENV}
    # Run web server on background
    - >
        vendor/bin/sculpin serve
        --env=${APP_ENV}
        --port=8080
        --no-ansi
        --no-interaction &

script:
    - >
        vendor/bin/behat
        --config=behat.yml.dist

after_script:
    # Stop web server
    - kill $!

after_success:
    - rm -rf source/assets
    - rm -rf output_${APP_ENV}
    - rm -rf vendor
    - >
        yarn install
        --production
    - >
        yarn add
        file-loader
        --dev
    - >
        yarn encore
        production
    - >
        composer install
        --prefer-dist
        --no-ansi
        --no-dev
        --no-interaction
        --no-progress
        --optimize-autoloader
        --ignore-platform-req php
    - >
        vendor/bin/sculpin generate
        --env=prod

deploy:
    provider:      pages
    skip_cleanup:  true
    github_token:  ${GITHUB_TOKEN}
    local_dir:     output_prod
    target_branch: main
    on:
        branch: develop
