language: php

os:   linux
dist: bionic
sudo: required

branches:
    only:
        - develop

cache:
    yarn: true
    directories:
        - ${HOME}/.composer/cache/files
        - node_modules

php:
    - '7.3'

install:
    - >
        yarn install
        --production
    - yarn encore production
    - >
        composer install
        --prefer-dist
        --no-ansi
        --no-dev
        --no-interaction
        --no-progress
        --optimize-autoloader

script:
    - vendor/bin/sculpin generate --env=prod

deploy:
    provider:       pages
    skip_cleanup:   true
    github_token:   ${GITHUB_TOKEN}
    local_dir:      output_prod
    target_branch:  master
    on:
        branch: develop
