version: "3.8"

services:
    nginx:
        image: ${DOCKER_IMAGE_NGINX}
        restart: always
        depends_on:
            - php
        command: >
            /bin/sh -c
            "envsubst $$APP_BASE_URL
            < /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"
        ports:
            - ${DOCKER_HOST_PORT_HTTP}:80
            - ${DOCKER_HOST_PORT_HTTPS}:443
        volumes:
            # folders
            - ../..:/var/www
            # files
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf.template:ro
        env_file:
            # docker
            - .env
            # application
            - ../../.env.local

    node:
        image: ${DOCKER_IMAGE_NODE_BASE}
        build:
            context: .
            dockerfile: ../docker/node/base/Dockerfile
            args:
                DOCKER_IMAGE_NODE: ${DOCKER_IMAGE_NODE}
        restart: on-failure
        command: node --version
        volumes:
            # folders
            - ../..:/var/www
        working_dir: /var/www
        env_file:
            # docker
            - .env
            # application
            - ../../.env.local
        user: ${DOCKER_HOST_UID}:${DOCKER_HOST_GID}

    php:
        image: ${DOCKER_IMAGE_PHP_DEV}
        build:
            context: ""
            dockerfile: ../docker/php/dev/Dockerfile
            args:
                DOCKER_IMAGE_PHP_BASE: ${DOCKER_IMAGE_PHP_BASE}
        restart: always
        volumes:
            # folders
            - ../..:/var/www
            - ${DOCKER_HOST_COMPOSER_HOME}:/composer
            # files
            - ./services/php/php-7.4.14-dev.ini:/usr/local/etc/php/php.ini:ro
            - ./services/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf:ro
            - ./services/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        working_dir: /var/www
        env_file:
            # docker
            - .env
            # application
            - ../../.env.local
        user: ${DOCKER_HOST_UID}:${DOCKER_HOST_GID}
